### ISSUE TITLE
Charons fake-arp (farp) plugin enabled by default.

### ISSUE THREAD

**Issue by thz** [openvnf/vnf-ipsec#11]
### Scenario/context:
1. vti interface and rightsubnet=0.0.0.0/0
2. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=703032#15

### Issue:
Incoming arp-requests on an independent interface are incorrectly answered by farp plugin.

### Proposal:
Do not load farp plugin by default.

**Comment by tlnd** [comment]
@grundrauschen this again has shown to be an issue. So please either disable farp by default or at least make it configurable via env var, so that we can disable it when using this. The workaround at present is, to disable it while starting the ipsec container:
```
      - command:
        - sh
        - -c
        - |
          # We have to patch configuration to remove f(ake)arp
          # plugin before actually starting strongswan...
          sed -i 's/load = yes/load = no/' /etc/strongswan.d/charon/farp.conf
          exec /usr/local/bin/start-strongswan.sh
```

**Comment by mgumz** [comment]
@tlnd rather than hacking around startup-scripts: what about just removing `/usr/lib/ipsec/plugins/libstrongswan-farp.so`?

**Comment by tlnd** [comment]
@mgumz I just provided the present workaround -- was not an advised solution. However, loading an unavailable plugin might also not be the right solution. So the default config should be adjusted to not load the farp plugin, IMHO.

**Comment by grundrauschen** [comment]
There was an error in my configuration of the IKE daemon *charon*, which resulted in ignoring the module load list.
Because enabling this option resulted in loading errors of depending libraries and using the load list is discouraged by the strongswan documentation, I switched back to using the module configuration and disabled `farp` by default.

I would though hesitate to add an environmental variable for every possible plugin.
I also do not see a use case where the use of the `farp` plugin would be useful for site-to-site VPN.

It is though possible to overwrite the configuration by mounting a modified module config.

I would not add increased configurability of the plugins before the rewrite.

Please review the changes in #16 and merge after successful review.

**Comment by grundrauschen** [comment]
Because the fix was merged I will close this issue.
The first working version is `v1.3.1`
